#!/usr/bin/env php
<?php

/**
 * Bootstrap Application
 */
require 'bootstrap.php';

/**
 * Create the application
 */
$application = new App\Application();

/**
 * Run the application
 */
$application->run();